<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-LeandroDeFRusso/blob/main/Pr%C3%A1ticas_com_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
#1
import numpy as np

array = np.zeros(10)

print(array)

print(array.dtype)
print(array.shape)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
(10,)


In [22]:
#2
import numpy as np

array = np.ones(10)

array_float = array.astype(np.float64)

print(array)
print(array_float)
print(array_float.dtype)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
float64
(10,)


In [24]:
#3
import numpy as np

array = np.arange(0, 10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#4
import numpy as np

array =